---
# tasks file for logrotate

- name: Assure logrotate is installed
  ansible.builtin.package:
    name: logrotate
    state: present

- name: Assure logrotate.d scripts exist
  ansible.builtin.template:
    src: logrotate.d.j2
    dest: "{{ logrotate_conf_dir }}{{ item.name }}"
    owner: root
    mode: 0644
    backup: true
  with_items: "{{ logrotate_scripts }}"
  when: logrotate_scripts is defined and logrotate_scripts|length > 0
